let langJSON={
    branchs: [
      {
        "id": "01",
        "ownerName": "Nagendra panwar",
        "branchCode": "IPG001",
        "companyName": "Speed cargo Packers and movers",
        "mobileNumber": "9369929666",
        "whatsApp": "7880600235",
        "mailIId": "speedcargoalld@gmail.com",
        "website": "Www.speedcargomovers.co.in",
        "address": "772, Transport Nagar, Mundera Rd, Sector 5, Dhoomanganj, Prayagraj, Uttar Pradesh 211011",
        "state": "Uttar Pradesh",
        "city": "Prayagraj",
        "gstNumber": "09BVGPK7619K1Z1"
      },
      {
        "id": "02",
        "ownerName": "DEEPAK sharma",
        "branchCode": "IPG002",
        "companyName": "Star Express Packers And Movers",
        "mobileNumber": "7722072277",
        "whatsApp": "9270927063",
        "mailIId": "starexpress.co.in@gmail.com",
        "website": "www.starexpress.co.in",
        "address": "Century Enka Colony, Bhosari, Pimpri-Chinchwad, Pune, Maharashtra 411039",
        "state": "Maharashtra",
        "city": "PCMC-Pune",
        "gstNumber": "27BZPPS4917K1ZJ"
      },
      {
        "id": "03",
        "ownerName": "Shiv Kumar Sharma",
        "branchCode": "IPG003",
        "companyName": "Om sai ram packers and movers",
        "mobileNumber": "7520869200",
        "whatsApp": "7252883355",
        "mailIId": "omsairampackers17@gmail.com",
        "website": "www.agrapackermover.com",
        "address": "Shop no 456 /6 mani transport nagar agra282002",
        "state": "Uttar pradesh",
        "city": "Agra",
        "gstNumber": "09BCIPK0721P1ZB"
      },
      {
        "id": "04",
        "ownerName": "DHARAMVEER PALIWAL",
        "branchCode": "IPG004",
        "companyName": "METRO RELOCATION AND TRANSPORTATION",
        "mobileNumber": "7359660007",
        "whatsApp": "8460003233",
        "mailIId": "info@metrorelocation.net",
        "website": "https://www.metrorelocation.net/",
        "address": "9/20 Vijay Enterprises CompoundNear Gurudwara,Silvasa Road Vapi-396191",
        "state": "GUJRAT",
        "city": "VAPI",
        "gstNumber": "null"
      },
      {
        "id": "05",
        "ownerName": "Shiv Ji Srivastava",
        "branchCode": "IPG005",
        "companyName": "Shanti ganga packers and movers",
        "mobileNumber": "7007904298",
        "whatsApp": "7007904298",
        "mailIId": "Shantigangapackers1@gmail.com",
        "website": "www.shantigangapackersandmovers.com",
        "address": "62 LGF Eldico Express plaza Eldico Udhan 2 Raibarily road Lucknow",
        "state": "Utter pradesh",
        "city": "Lucknow",
        "gstNumber": "09BFDPS5421Q1ZT"
      },
      {
        "id": "06",
        "ownerName": "Vijender Kumar",
        "branchCode": "IPG006",
        "companyName": "Aadinath Packers And Movers",
        "mobileNumber": "9212672222",
        "whatsApp": "9212672222",
        "mailIId": "vijenderkumar1989@gmail.com",
        "website": "www.aadinathpackers.com ",
        "address": "313/4 3rd floor patel garden E Block dwarka more new delhi-110078",
        "state": "Delhi",
        "city": "Delhi",
        "gstNumber": "07BLKPK4996H1ZI"
      },
      {
        "id": "07",
        "ownerName": "KRISHNA JHA",
        "branchCode": "IPG007",
        "companyName": "SHIVAM PACKERS AND MOVERS",
        "mobileNumber": "7999514724",
        "whatsApp": "7869581679",
        "mailIId": "shivampackers2611@gmail.com",
        "website": "www.shivampackersandmover.com",
        "address": "1st floor shiv vihar colony lane 2 mahmand Bilaspur Chhattisgarh 495004",
        "state": "Chhattisgarh",
        "city": "Bilaspur",
        "gstNumber": "22AQBPJ0185E1ZG"
      },
      {
        "id": "08",
        "ownerName": "Sandeep Poonia",
        "branchCode": "IPG008",
        "companyName": "Eagle relocation India",
        "mobileNumber": "9960727272",
        "whatsApp": "9960727272",
        "mailIId": "eaglerelocationmumbai@gmail.com",
        "website": "www.eaglerelocationindia.com",
        "address": "Office no 7 shukla niwas group no 6 near guru govind singh garden Tagore Nagar Vikhroli East Mumbai Maharashtra 400083",
        "state": "Maharashtra",
        "city": "Mumbai",
        "gstNumber": "27DRZPP8709J1ZM"
      },
      {
        "id": "09",
        "ownerName": "Bajrang Sharma",
        "branchCode": "IPG009",
        "companyName": "Gayatri packers and movers",
        "mobileNumber": "9011489333",
        "whatsApp": "9011489333",
        "mailIId": "gayatripackers@gmail.com",
        "website": "www.gayatripackersandmovers.co.in",
        "address": "ASC 27 Ahhwin nagar cidco Nashik 9",
        "state": "Maharashtra",
        "city": "Nashik",
        "gstNumber": "null"
      },
      {
        "id": "10",
        "ownerName": "Anil Chaudhari",
        "branchCode": "IPG010",
        "companyName": "NETWORK CARGO PACKERS AND MOVERS",
        "mobileNumber": "9673149000",
        "whatsApp": "9673149000",
        "mailIId": "networkpackersmh@gmail.com",
        "website": "www.networkmovers.in ",
        "address": "Lal Mitti Deolai Road Near Wine Shop Aurangabad 431001",
        "state": "Maharashtra",
        "city": "Aurangabad",
        "gstNumber": "27CQBPD3887K1ZI"
      },
      {
        "id": "11",
        "ownerName": "Rajesh Kumar",
        "branchCode": "IPG011",
        "companyName": "Bangalore King Logistics",
        "mobileNumber": "9886526564",
        "whatsApp": "9341624783",
        "mailIId": "Info@bklindia.com",
        "website": "Www.bklindia.com",
        "address": "Shop number 41 Jai bharat parking tci bas stop 18km madavara post Bangalore 562123 madanayakanahalli.",
        "state": "Karnataka",
        "city": "Bangalore",
        "gstNumber": "29cdspk5484k2zj"
      },
      {
        "id": "74",
        "ownerName": "Viviek Misha",
        "branchCode": "IPG013",
        "companyName": "Shree Ram Relocation",
        "mobileNumber": "9294860616",
        "whatsApp": "9294860616",
        "mailIId": "honeypackersandmovers1@gmail.com",
        "website": "https://www.honeypackersandmovers.in/",
        "address": "Ward No. 14 Block 12 Shop. No 15, Transport Nagar, Rawabhata, Raipur Ho, Raipur-Chhattisgarh - 492001",
        "state": "Chhattisgarh",
        "city": "Raipur",
        "gstNumber": "22CHGPS3346L2Z2"
      },
      {
        "id": "12",
        "ownerName": "Manish Tiwari",
        "branchCode": "IPG014",
        "companyName": "Gyanshree Relocations Pvt.Ltd",
        "mobileNumber": "9559978703",
        "whatsApp": "9455350034",
        "mailIId": "Gyanshreepackers1266@gmail.com",
        "website": "Www.gyanshreepackers.com",
        "address": "Shop No 03 Yadav complex chandpur Industrial Estate Varanasi (UP)221106",
        "state": "Uttarpradesh",
        "city": "Varanasi",
        "gstNumber": "09AUBPT7286Q2ZG"
      },
      {
        "id": "13",
        "ownerName": "ASHWANI KUMAR",
        "branchCode": "IPG015",
        "companyName": "SHARMA PACKERS&MOVERS",
        "mobileNumber": "8400801981",
        "whatsApp": "7309438105",
        "mailIId": "vanshvansh2312@gmail.com",
        "website": "NO",
        "address": "41/E JYOTI VILLA SHANTI NAGAR DARGAHIYA KUNRAGHAT GORAKHPUR",
        "state": "UTTAR PRADESH",
        "city": "GORAKHPUR",
        "gstNumber": "09CDQPK5318C1ZG"
      },
      {
        "id": "14",
        "ownerName": "Ramesh Jakhar",
        "branchCode": "IPG016",
        "companyName": "Professional Home Relocation",
        "mobileNumber": "8891991199",
        "whatsApp": "8891991199",
        "mailIId": "professionalhomerelocationcok@gmail.com",
        "website": "www.professionalhomerelocation.in",
        "address": "11/286A, Kallarackal House, Pallilamkara Rockwell Nad Road Near HMT Post office Kalamassery Ernakulam Cochin kerala 683503",
        "state": "Kerala",
        "city": "Cochin",
        "gstNumber": "32BGDPK9196D1ZD"
      },
      {
        "id": "15",
        "ownerName": "Nanda kishor Pattanaik",
        "branchCode": "IPG017",
        "companyName": "Decan Packers & Movers",
        "mobileNumber": "9338659299",
        "whatsApp": "9439255512",
        "mailIId": "decanmoversbbsr@gmail.com",
        "website": "www.decanpackersandmovers.com",
        "address": "Hig 2/37.BDA Colony.Kapilaprasad.Bhubaneswar.Odisha.751002.",
        "state": "Odisha",
        "city": "Bhubaneswar",
        "gstNumber": "21AXYPP9114F1Z6"
      },
      {
        "id": "16",
        "ownerName": "RAM SURAT SAHANI",
        "branchCode": "IPG018",
        "companyName": "ADARSH PACKERS AND MOVERS",
        "mobileNumber": "7008893251",
        "whatsApp": "7008893251",
        "mailIId": "ramsuratsahani890@gmail.com",
        "website": "www.adarshpackers.in",
        "address": "At bhangamunda,po- remed, dist-sambalpur768006,odisha",
        "state": "Odisha",
        "city": "SAMBALPUR",
        "gstNumber": "21AVOPS6289G1Z1"
      },
      {
        "id": "17",
        "ownerName": "Naresh kumar choudhary",
        "branchCode": "IPG020",
        "companyName": "Bala Ji packers and movers",
        "mobileNumber": "9377005333",
        "whatsApp": "8460050001",
        "mailIId": "balajipackersrajkot@gmail.com",
        "website": "https://balajipackernmovers.com/",
        "address": "101 haridwar park opp Pankaj transport behind kuwadwa road police station Nvagam rajkot",
        "state": "Gujarat",
        "city": "Rajkot",
        "gstNumber": "24DDUPK9481B1Z5"
      },
      {
        "id": "18",
        "ownerName": "Prahlad Sharma",
        "branchCode": "IPG021",
        "companyName": "Shree Siddhivinayak Packers and movers Surat Gujarat",
        "mobileNumber": "9376032233",
        "whatsApp": "9376032233",
        "mailIId": "shreesiddhivinayakpackers33@gmail.com",
        "website": "www.ssvpm.in",
        "address": "85 Vijay nagar Hari Nagar 2 udhana Surat Gujarat 394210",
        "state": "Gujrat",
        "city": "Surat",
        "gstNumber": "24AROPP3183EIZN"
      },
      {
        "id": "19",
        "ownerName": "Manoj roy",
        "branchCode": "IPG023",
        "companyName": "Aadinath Packers And Movers",
        "mobileNumber": "9017700900",
        "whatsApp": "9017700900",
        "mailIId": "vijenderkumar1989@gmail. com",
        "website": "www.aadinathpackers.com ",
        "address": "Palam vihar Gurgaon",
        "state": "Haryana",
        "city": "Gurugram",
        "gstNumber": "07BLKPK4996H1ZI"
      },
      {
        "id": "20",
        "ownerName": "Satish Sharma",
        "branchCode": "IPG024",
        "companyName": "V Trans Cargo movers",
        "mobileNumber": "9898477829",
        "whatsApp": "7433001129",
        "mailIId": "Gandhidham@Vtranscargomovers.com",
        "website": "www.vtranscargomovers.com",
        "address": "H no 133 ground floor arihant nager Rs 118/1 Megpar Borichi anjar 370110",
        "state": "Gujarat",
        "city": "Gandhidham",
        "gstNumber": "24BKBPK1979A1ZI"
      },
      {
        "id": "21",
        "ownerName": "Sunit Bhatnagar",
        "branchCode": "IPG025",
        "companyName": "Shubham Packers And Movers",
        "mobileNumber": "9718592377",
        "whatsApp": "9718592377",
        "mailIId": "sukeshbhatnagar85@gmail.com",
        "website": "www.shubhampackersandmover.in",
        "address": "B-1010 Green Field Colony Sector 43 Faridabad Haryana -121001",
        "state": "Haryana",
        "city": "Faridabad",
        "gstNumber": "06ATOPB3967G1ZJ"
      },
      {
        "id": "22",
        "ownerName": "Syed Masood",
        "branchCode": "IPG026",
        "companyName": "AK Packers and Movers",
        "mobileNumber": "9886415786",
        "whatsApp": "9886415786",
        "mailIId": "aklsdvg@gmail.com",
        "website": "https://akpackers.com/",
        "address": "AK PACKERS AND MOVERS\r\r\nNME BUILDING ONION MARKET PB ROAD",
        "state": "Karnataka",
        "city": "DAVANAGERE"
      },
      {
        "id": "23",
        "ownerName": "SADANAND KUMAR",
        "branchCode": "IPG027",
        "companyName": "No.1 Packers N Movers",
        "mobileNumber": "9311567331",
        "whatsApp": "9311567331",
        "mailIId": "no1packersnmovers01@gmail.com",
        "website": "www.no1packers.com",
        "address": "Shop no.1, Krishna Tower, Sarfabad, Sec 73, Noida, (UP) - 201301",
        "state": "Uttar Pradesh",
        "city": "Noida",
        "gstNumber": "07IXKPK9290K1ZJ"
      },
      {
        "id": "24",
        "ownerName": "BALJIT JANGRA",
        "branchCode": "IPG028",
        "companyName": "DHL MOVERS PACKERS PVT LTD",
        "mobileNumber": "9392225387",
        "whatsApp": "9392225387",
        "mailIId": "info@dhlmoverspackers.com",
        "website": "www.dhlmoverspackers.com",
        "address": "# 3-4-15/20/1/2 Blue Birds Calony Bolarum Secunderabad",
        "state": "Telangana",
        "city": "Hyderabad",
        "gstNumber": "36AAGCE4753R1ZY"
      },
      {
        "id": "25",
        "ownerName": "Narendra Singh",
        "branchCode": "IPG030",
        "companyName": "Bhagwati packers and movers",
        "mobileNumber": "9610122423",
        "whatsApp": "9766665865",
        "mailIId": "bhagawatimoverspackerspune@gmail.com",
        "website": "www.bhagwatipackersandmovers.com",
        "address": "Plot no 29 sector no 23 transport Nagar Nigdi Pune Maharashtra 411044",
        "state": "Maharashtra",
        "city": "PUNE",
        "gstNumber": "27DHVPS3066P1Z4"
      },
      {
        "id": "26",
        "ownerName": "Murari lal",
        "branchCode": "IPG031",
        "companyName": "Bankey bihari packers and movers",
        "mobileNumber": "8755990906",
        "whatsApp": "8755990906",
        "mailIId": "bankeybiharipackersmovers@gmail.com",
        "website": "Bankeybiharipackersandmovers.com",
        "address": "OPP kali mata mandir kali badi Bareilly",
        "state": "Uttar Pradesh",
        "city": "bareilly",
        "gstNumber": "09AMDPL1640G1ZA"
      },
      {
        "id": "27",
        "ownerName": "Monesh Sharma",
        "branchCode": "IPG032",
        "companyName": "India's no.1 Packers And Movers",
        "mobileNumber": "8827260588",
        "whatsApp": "9691776832",
        "mailIId": "indiasnopackersandmovers@gmail.com",
        "website": "http://indiasno1packersandmovers.com/",
        "address": "Sheel Nagar Near Bajarang Garden Ghash Mandi Road Gwalior MP",
        "state": "Madhya Pradesh",
        "city": "Gwalior",
        "gstNumber": "23HZEPS9394P2Z4"
      },
      {
        "id": "28",
        "ownerName": "Anil Hindurao Sawant",
        "branchCode": "IPG033",
        "companyName": "Sakshi packers and movers",
        "mobileNumber": "7744889191",
        "whatsApp": "7744889191",
        "mailIId": "anilsawant400528@gmail.com",
        "website": "www.sakshipackerandmover.com",
        "address": "2184 c ward near sharda cafe opp swayambhu ganesh mandir laxmipuri kolhapur 416002",
        "state": "Maharashtra",
        "city": "Kolhapur",
        "gstNumber": "27BZNPS6619E1ZV"
      },
      {
        "id": "29",
        "ownerName": "FAROOQ",
        "branchCode": "IPG035",
        "companyName": "ROYALCARE PACKERS AND MOVERS",
        "mobileNumber": "9663088086",
        "whatsApp": "9148049883",
        "mailIId": "royalcarepackersandmovers@gmail.com",
        "website": "www.Royalcarepackers.In",
        "address": "BARLANE ROAD CHICKMAGALUR",
        "state": "KARNATAKA",
        "city": "CHICKMAGALUR",
        "gstNumber": "29ACCPF2581R123"
      },
      {
        "id": "30",
        "ownerName": "G.GANGARAJU",
        "branchCode": "IPG036",
        "companyName": "GVK PACKERS AND MOVERS",
        "mobileNumber": "9000094945",
        "whatsApp": "9000094945",
        "mailIId": "gvkpackers.movers@gmail.com",
        "website": "www.gvkpackersandmovers.com",
        "address": "D.NO.36-4-13, temple street, kakinada",
        "state": "Andhrapradesh",
        "city": "Kakinada",
        "gstNumber": "37AVJPG8432E1ZK"
      },
      {
        "id": "31",
        "ownerName": "Sattibabu boddeti",
        "branchCode": "IPG037",
        "companyName": "Nandini packers and movers",
        "mobileNumber": "9441944590",
        "whatsApp": "9441944590",
        "mailIId": "nandinipackersandmovers@gmail.com",
        "website": "https://g.co/kgs/K3jbK3",
        "address": "Nandini Packers & Movers\r\r\n\r\r\n#54-7-24, Beside Surishetty Krishna Complex, opp. Indian Oil Petrol Bunk, Isukathota, Visakhapatnam, Andhra Pradesh 530022",
        "state": "Andhra Pradesh",
        "city": "Visakhapatnam",
        "gstNumber": "37ATUPB3061D1ZT"
      },
      {
        "id": "32",
        "ownerName": "C.venugopal",
        "branchCode": "IPG038",
        "companyName": "Indian packers and movers",
        "mobileNumber": "9951873738",
        "whatsApp": "9951873738",
        "mailIId": "venugopal3738@gmail.com",
        "website": "Indian packers and movers ballary",
        "address": "Belgal cross road, ballary",
        "state": "Karnataka",
        "city": "Ballary",
        "gstNumber": "37KVFPK6407P1ZS"
      },
      {
        "id": "33",
        "ownerName": "Vikram Kumar Chahar",
        "branchCode": "IPG039",
        "companyName": "Metro Relocation And Transportation",
        "mobileNumber": "8733034403",
        "whatsApp": "8733034403",
        "mailIId": "Ahmd@metropacker.com",
        "website": "www.metrorelocation.net",
        "address": "Godown number 5 Radhe state B/H Shell petrol pump aslali",
        "state": "Gujarat",
        "city": "Ahmedabad",
        "gstNumber": "24BANPD0969F1ZS"
      },
      {
        "id": "35",
        "ownerName": "ROHIT KUMAR",
        "branchCode": "IPG040",
        "companyName": "METRO RELOCATION AND TRANSPORTATION",
        "mobileNumber": "7665600077",
        "whatsApp": "7665600077",
        "mailIId": "Metrorelocarionjpr@gmail.com",
        "website": "Www.metropacker.com",
        "address": "E256 NARAYAN VIHAR NEAR GANESH PERADISE ,JAIPUR",
        "state": "RAJASTHAN",
        "city": "JAIPUR",
        "gstNumber": "24BANPD0969F1ZS"
      },
      {
        "id": "36",
        "ownerName": "PRABHAT KUMAR JHA",
        "branchCode": "IPG041",
        "companyName": "EASY MOVES INTERNATIONAL PACKERS AND MOVERS PRIVATE LIMITED",
        "mobileNumber": "7979767957",
        "whatsApp": "9973019485",
        "mailIId": "easymovesinternational@gmail.com",
        "website": "www.easymoves.co.in",
        "address": "VIP COLONY GHANA COLONY ROAD RAMAKRISHNA NAGAR PATNA 800020",
        "state": "BIHAR",
        "city": "PATNA",
        "gstNumber": "07AAECE9404F1ZS"
      },
      {
        "id": "37",
        "ownerName": "Sajjan Singh",
        "branchCode": "IPG042",
        "companyName": "SRS PACKERS AND MOVERS",
        "mobileNumber": "9892325154",
        "whatsApp": "9892325154",
        "mailIId": "srsmoversmumbai@gmail.com",
        "website": "Www.srspackersandmovers.com",
        "address": "Shop No.5,Sky Oasis,Plot No.29, Sector 9, Ulwe, Navi Mumbai, Maharashtra 410206",
        "state": "Maharashtra",
        "city": "Navi Mumbai",
        "gstNumber": "08GMBPS5559D1ZP"
      },
      {
        "id": "38",
        "ownerName": "Sanjay poonia",
        "branchCode": "IPG043",
        "companyName": "Eagle Relocation india",
        "mobileNumber": "9896967899",
        "whatsApp": "9896957899",
        "mailIId": "eaglerelocationnoida@gmail.com",
        "website": "www.eaglerelocationindia.com",
        "address": "Office No 18 richpal gaddi near Gaur City 2 Greater Noida 201301",
        "state": "Uttar Pradesh",
        "city": "Greater Noida",
        "gstNumber": "09JIYPK8086R1Z0"
      },
      {
        "id": "39",
        "ownerName": "Jitender sharma",
        "branchCode": "IPG044",
        "companyName": "Aushman transport division of Packers and movers",
        "mobileNumber": "8848907189",
        "whatsApp": "8848907189",
        "mailIId": "Jitusharmakatak@gmail.com",
        "website": "https://www.ayushmanpackersandmovers.com/#",
        "address": "Shop number 1,2 Kohale Layout Khadgaon road Wadi Nagpur 440023",
        "state": "Maharashtra",
        "city": "Nagpur",
        "gstNumber": "27HBEPK8057F1ZD"
      },
      {
        "id": "40",
        "ownerName": "Sunil Sharma",
        "branchCode": "IPG046",
        "companyName": "Gayatri Packers and movers",
        "mobileNumber": "8472057230",
        "whatsApp": "8472057230",
        "mailIId": "Info@gayatripackersindia.com",
        "website": "www.gayatripackersindia.com",
        "address": "House no 30, ground floor Frist left side, near income tax colony, Bangaon Beltola Guwahati Assam 781028",
        "state": "Assam",
        "city": "Guwahati",
        "gstNumber": "null"
      },
      {
        "id": "41",
        "ownerName": "Nageshwar Thakur",
        "branchCode": "IPG047",
        "companyName": "SHRI Ganpati Packers and movers",
        "mobileNumber": "7065633611",
        "whatsApp": "7065633611",
        "mailIId": "shriganpati70@gmail.com",
        "website": "www.shriganpatipackersandmovers.in",
        "address": "Kapil Vihar.steet.no1 Mukandpur Part 2",
        "state": "Dehli",
        "city": "Delhi",
        "gstNumber": "07AFPPT588H2ZK"
      },
      {
        "id": "42",
        "ownerName": "SAKE.MUSALAIAH",
        "branchCode": "IPG048",
        "companyName": "SRI GOWRI PACKERS and MOVERS",
        "mobileNumber": "7680903974",
        "whatsApp": "7680903974",
        "mailIId": "srigowripackersandmovers@gmail.com",
        "website": "www.srigowripackersandmovers.com",
        "address": "SV Digree College Jesus nagar Anantapur Andhra Pradesh",
        "state": "Andhra Pradesh",
        "city": "ANANTAPUR",
        "gstNumber": "37FQEPM1054B1Z6"
      },
      {
        "id": "43",
        "ownerName": "NOOKESH KOSANAM",
        "branchCode": "IPG049",
        "companyName": "MAHI PACKERS AND MOVERS",
        "mobileNumber": "9133224100",
        "whatsApp": "9133224100",
        "mailIId": "infomahipackers@gmail.com",
        "website": "www.mahipackers.in",
        "address": "LIG-6 B-BLOCK APIIC MAIN ROAD AUTONAGAR VISAKHAPATNAM - 530012",
        "state": "ANDHRA PRADESH",
        "city": "VISAKHAPATNAM",
        "gstNumber": "37COAPK5027H2Z1"
      },
      {
        "id": "44",
        "ownerName": "Ravi Singh",
        "branchCode": "IPG051",
        "companyName": "Rajput Packers And Movers",
        "mobileNumber": "8017748993",
        "whatsApp": "8017748993",
        "mailIId": "rs3477738@gmail.com",
        "website": "www.rajputpackers.in",
        "address": "H/H 10/1, Near Vip Road, Baguihati, Kolkata, West Bengal, 700059",
        "state": "West Bengal",
        "city": "Kolkata",
        "gstNumber": "19UTPS7105H1ZW"
      },
      {
        "id": "45",
        "ownerName": "Sajjan Kumar Sharma",
        "branchCode": "IPG052",
        "companyName": "Pragati Express Packers and Movers",
        "mobileNumber": "9301212720",
        "whatsApp": "9301212720",
        "mailIId": "sk.sharma39@yahoo.com",
        "website": "www.pragatiexpresspackers.com",
        "address": "Shop no 6/33 T.T.Nagar, behind Kataria complex,Near metro wholesale,Dewas Naka, Indore 452010 M.P.",
        "state": "Madhya Pradesh",
        "city": "Indore",
        "gstNumber": "23BDKPS5130H1ZL"
      },
      {
        "id": "46",
        "ownerName": "Ritik Singh",
        "branchCode": "IPG053",
        "companyName": "Rajput Packers And Movers",
        "mobileNumber": "9748886078",
        "whatsApp": "9748886078",
        "mailIId": "rajputpackers@gmail.com",
        "website": "www.rajputpackers.in",
        "address": "Ground Floor, Shop.4, Holding.547/j1, Kishore Ganj, Anand Nagar, Harmu Road, Ranchi, Pin-834001",
        "state": "Jharkhand",
        "city": "Ranchi",
        "gstNumber": "20EUTPS7105H1ZW"
      },
      {
        "id": "47",
        "ownerName": "Pandav Kumar",
        "branchCode": "IPG056",
        "companyName": "Shri Ganpati Packers & Movers",
        "mobileNumber": "7970919859",
        "whatsApp": "7970919859",
        "mailIId": "shriganpati70@gmail.com",
        "website": "www.shriganpatipackersandmovers.in",
        "address": "Delhi mor, AllalPatti Road, Krishnapuri, Darbhanga, Bihar",
        "state": "Bihar",
        "city": "Darbhanga",
        "gstNumber": "07AFPPT5884H2ZK"
      },
      {
        "id": "48",
        "ownerName": "Pandav Kumar",
        "branchCode": "IPG057",
        "companyName": "Shri Ganpati Packers & Movers",
        "mobileNumber": "7970919859",
        "whatsApp": "7970919859",
        "mailIId": "Shriganpati70@gmail.com",
        "website": "www.shriganpatipackersandmovers.in",
        "address": "Delhi More, Allalpatti Road, Krishnapuri,Darbhanga, Bihar",
        "state": "Bihar",
        "city": "Darbhanga",
        "gstNumber": "07AFPPT5884H2ZK"
      },
      {
        "id": "49",
        "ownerName": "Ganesh nagu ch",
        "branchCode": "IPG012",
        "companyName": "Surya packers and movers",
        "mobileNumber": "9492872666",
        "whatsApp": "9848691166",
        "mailIId": "suryapackers9@gmail.com",
        "website": "Suryapackersmovers.co.in",
        "address": "Hukum pet,godavari ruchuli",
        "state": "ANDHRA PRADESH",
        "city": "RAJAHMUNDRY",
        "gstNumber": "37AVYPC3565H2Z2"
      },
      {
        "id": "50",
        "ownerName": "Ravinder",
        "branchCode": "IPG060",
        "companyName": "The falcons contractors",
        "mobileNumber": "7056371186",
        "whatsApp": "7056371186",
        "mailIId": "thefalcons.0786@gmail.com",
        "website": "www.aadinathmovers.com",
        "address": "Ghaziabad",
        "state": "UP",
        "city": "Ghaziabad",
        "gstNumber": "06BKIPR9011H1Z1"
      },
      {
        "id": "51",
        "ownerName": "Bhaskar s",
        "branchCode": "IPG062",
        "companyName": "Ramesh Packers And Movers",
        "mobileNumber": "9113848456",
        "whatsApp": "9113848456",
        "mailIId": "bhaskar67975@gmail.com",
        "website": "www.rameshpackersandmovers.com",
        "address": "B301.Inchara himadri road 4th main road ward 10.jaynagar 2nd stage beside holy cross sisters high school Hassan 573202",
        "state": "Karantaka",
        "city": "Hassan",
        "gstNumber": "No"
      },
      {
        "id": "52",
        "ownerName": "M GOPINKRISHNA",
        "branchCode": "IPG063",
        "companyName": "MOVING SOLUTION PACKERS AND MOVERS",
        "mobileNumber": "9642677666",
        "whatsApp": "9642677666",
        "mailIId": "Movingsolutionspackersmovers@gmail.com",
        "website": "https://www.movingsolutionspackersandmovers.com/",
        "address": "Near PVP MALL , BENZ CIRCLE , VIJAYAWADA",
        "state": "Andhra Pradesh",
        "city": "VIJAYAWADA",
        "gstNumber": "NA"
      },
      {
        "id": "53",
        "ownerName": "Ashu Sharma",
        "branchCode": "IPG064",
        "companyName": "INSTANT RELOCATIONS",
        "mobileNumber": "9144910460",
        "whatsApp": "7389995756",
        "mailIId": "Instantrelocations@gmail.com",
        "website": "www.instantrelocations.com",
        "address": "Near Punjab National Bank, opp Bus Stand Rewa Road, Satna, MP",
        "state": "Madhya Pradesh",
        "city": "Satna",
        "gstNumber": "23MJDPS3356R1ZB"
      },
      {
        "id": "54",
        "ownerName": "Sourav Sharma",
        "branchCode": "IPG065",
        "companyName": "Pyramid Packers",
        "mobileNumber": "9316002444",
        "whatsApp": "9316002444",
        "mailIId": "pyramidpackers@gmail.com",
        "website": "Pyramidpackers.com",
        "address": "F95 Transport Nagar",
        "state": "Uttarakhand",
        "city": "Dehradun"
      },
      {
        "id": "55",
        "ownerName": "Arunkumar G",
        "branchCode": "IPG067",
        "companyName": "Sri Vinayaga packers and movers",
        "mobileNumber": "9710815533",
        "whatsApp": "9710815533",
        "mailIId": "srivinayagapackersmovers @gmail.com",
        "website": "Nil",
        "address": "1/18 Vambuli Naicker street Vanagaram",
        "state": "Tamil Nadu",
        "city": "Chennai",
        "gstNumber": "null"
      },
      {
        "id": "56",
        "ownerName": "Monesh Sharma",
        "branchCode": "IPG068",
        "companyName": "INDIA'S NO.1 PACKERS AND MOVERS",
        "mobileNumber": "9691776832",
        "whatsApp": "8827260588",
        "mailIId": "indiasnopackersandmovers@gmail.com",
        "website": "http://indiasno1packersandmovers.com/",
        "address": "Maharajpur transport nagar Near by Narmada Leborite Centre Karonda Nala Jabalpur MP",
        "state": "Madhya Pradesh",
        "city": "Jabalpur mp",
        "gstNumber": "23HZEPS9394P2Z4"
      },
      {
        "id": "57",
        "ownerName": "K PAVAN KUMAR",
        "branchCode": "IPG069",
        "companyName": "PAVAN RELOCATIONS MOVERS & PACKERS",
        "mobileNumber": "9396930999",
        "whatsApp": "9396930999",
        "mailIId": "pavanrelocations@gamil.con",
        "website": "Pavanrelocation.com",
        "address": "D.NO 7/108,, Kotramangalam Road, Tiruchanoor, Tirupati - 517503 (Padmavati Conventional Centre)",
        "state": "Andhra Pradesh",
        "city": "TIRUPATI",
        "gstNumber": "37EVEPK0029J1ZL"
      },
      {
        "id": "58",
        "ownerName": "MR VITTHALLA",
        "branchCode": "IPG071",
        "companyName": "RAMESH RELOCATIONS",
        "mobileNumber": "9886172172",
        "whatsApp": "9986172172",
        "mailIId": "INFO@RAMESHRELOCATIONS.COM",
        "website": "WWW.RAMESHRELOCATIONS.COM",
        "address": "2nd phase, 122/4, Vijayanagar 4th Stage, Vijayanagar, Mysuru, Karnataka 570017",
        "state": "KARNATAKA",
        "city": "MYSURU",
        "gstNumber": "null"
      },
      {
        "id": "59",
        "ownerName": "Akash tomar",
        "branchCode": "IPG072",
        "companyName": "Safe fast packers and movers Aligarh",
        "mobileNumber": "9536700381",
        "whatsApp": "9536700381",
        "mailIId": "akashtomarakaahtomar828@gmail.com",
        "website": "Safefastpackersandmovers.com",
        "address": "Ramghat roadQuarsi choraha paranjali ke pass",
        "state": "Up",
        "city": "Aligarh",
        "gstNumber": "09gnypk9921h2zz"
      },
      {
        "id": "61",
        "ownerName": "Mohit Kumar",
        "branchCode": "IPG073",
        "companyName": "Indian international packers and movers",
        "mobileNumber": "8791203144",
        "whatsApp": "8791203145",
        "mailIId": "iipm2021@gmail.com",
        "website": "www.indianinternationalpackersandmovers.com",
        "address": "Noor Nagar railway station main road lisari meerut.250002",
        "state": "Uttar Pradesh",
        "city": "Meerut",
        "gstNumber": "null"
      },
      {
        "id": "62",
        "ownerName": "Rakesh Guleria",
        "branchCode": "IPG074",
        "companyName": "BRS INDIA PACKERS MOVERS",
        "mobileNumber": "9328970777",
        "whatsApp": "8238937363",
        "mailIId": "rakesh.guleria1987@gmail.com",
        "website": "www.brsindiapackers.com",
        "address": "Ff 143 Shri Hari township ajwa road Vadodara 390019",
        "state": "gujrat",
        "city": "baroda",
        "gstNumber": "24AJOPT1285F2ZX"
      },
      {
        "id": "63",
        "ownerName": "NAGESH ANIL NAVALE",
        "branchCode": "IPG075",
        "companyName": "BALAJI PACKERS AND MOVERS SANGLI",
        "mobileNumber": "9284788415",
        "whatsApp": "7744000915",
        "mailIId": "navalenagesh770@gmail.com",
        "website": "https://balaji-packers-and-movers-in-sangli.business.site/",
        "address": "Shop No 1, Ganesh Apartment, Mahavir Nagar. Vakharbag,. Sangli",
        "state": "Maharashtra",
        "city": "Sangli"
      },
      {
        "id": "64",
        "ownerName": "Harish saini",
        "branchCode": "IPG076",
        "companyName": "Tanvi movers packers",
        "mobileNumber": "7500771973",
        "whatsApp": "7017861392",
        "mailIId": "hs399973@ gmail.Com",
        "website": "tanvimovers.co.in",
        "address": "Chau ki basti Linepar,",
        "state": "up",
        "city": "Moradabad",
        "gstNumber": "O9FJDPS1159H1ZW"
      },
      {
        "id": "65",
        "ownerName": "Bishnu prakash dash",
        "branchCode": "IPG077",
        "companyName": "RUDRA packers and movers Pvt ltd",
        "mobileNumber": "9752586113",
        "whatsApp": "9078351155",
        "mailIId": "rudrapackersandmovers123@gmail.com",
        "website": "www.rudrapackersandmovers.com",
        "address": "Basanti colony rourkela odisha",
        "state": "Odisha",
        "city": "Rourkela",
        "gstNumber": "21aakcr7027h1zg"
      },
      {
        "id": "66",
        "ownerName": "Manoj Kumar bhol",
        "branchCode": "IPG078",
        "companyName": "RUDRA packers and movers Pvt ltd",
        "mobileNumber": "8249208934",
        "whatsApp": "8249208934",
        "mailIId": "rudrapackersandmovers123@gmail.com",
        "website": "www.rudrapackersandmovers.com",
        "address": "Slag road,Jamshedpur, Jharkhand",
        "state": "Jharkhand",
        "city": "Jamshedpur",
        "gstNumber": "21aakcr7027h1zg"
      },
      {
        "id": "67",
        "ownerName": "Vinod Vats",
        "branchCode": "IPG079",
        "companyName": "Eagle Relocation India",
        "mobileNumber": "9855969898",
        "whatsApp": "9855969898",
        "mailIId": "eaglerelocationchd@gmail.com",
        "website": "www.eaglerelocationindia.com",
        "address": "156 GURDEV NAGAR,",
        "state": "PB",
        "city": "ZIRKPUR",
        "gstNumber": "03CATPS0970C3ZL"
      },
      {
        "id": "68",
        "ownerName": "Pankaj Kumar dixit",
        "branchCode": "IPG080",
        "companyName": "Shiva best Packers and movers",
        "mobileNumber": "9532874483",
        "whatsApp": "9452381185",
        "mailIId": "Shivabestpackers@gmail.com",
        "website": "WWW.Shivabestpackers.com",
        "address": "52/43C Nai Dal mandi. Nayaganj,. Above Hotal. Krishna galaxy Kanpur",
        "state": "UP",
        "city": "Kanpur",
        "gstNumber": "09BGEPD0028A2Z8"
      },
      {
        "id": "69",
        "ownerName": "Sohan Adhikari",
        "branchCode": "IPG081",
        "companyName": "Adhikari Packers and Movers",
        "mobileNumber": "8240146830",
        "whatsApp": "8240146830",
        "mailIId": "adhikaripackersandmovers@gmail.com",
        "website": "www.adhikaripackersmovers@gmail.com",
        "address": "Monoharpur Swarup Nagar Lane No. 2, Dankuni Hooghly",
        "state": "West Bengal",
        "city": "Kolkata",
        "gstNumber": "null"
      },
      {
        "id": "70",
        "ownerName": "J Durga Prasad",
        "branchCode": "IPG082",
        "companyName": "Apple packers and movers",
        "mobileNumber": "9542080555",
        "whatsApp": "9542080555",
        "mailIId": "applepackersandmovervja@Gmail.com.",
        "website": "www.applepackersandmovers.com",
        "address": "33_23_7 krishnarao street gandhibommala street Kasturi Bai pet vijayawada AP.",
        "state": "Andhra Pradesh",
        "city": "Vijayawada",
        "gstNumber": "37ALEPJ39081ZD"
      },
      {
        "id": "71",
        "ownerName": "Abhimanyu Khatri",
        "branchCode": "IPG083",
        "companyName": "Parkash packers and movers",
        "mobileNumber": "9784543728",
        "whatsApp": "9784543728",
        "mailIId": "parkashkhatri978@gmail.com",
        "website": "https://www.parkashpackersmovers.com/",
        "address": "Pandit ji petrol pump ke pass new gajner road",
        "state": "Rajasthan",
        "city": "Bikaner",
        "gstNumber": "08DNFPK0951R1ZF"
      },
      {
        "id": "72",
        "ownerName": "Suresh",
        "branchCode": "IPG084",
        "companyName": "Suresh Packers and Movers",
        "mobileNumber": "7402066555",
        "whatsApp": "7402066555",
        "mailIId": "sureshpacmov@gmail.com",
        "website": "www.sureshpacmon.in",
        "address": "Plot No-633 , Near VH Complex, Steel Plant Main Road, Om Sakthi Nagar , Salem-636304",
        "state": "Tamilnadu",
        "city": "Salem",
        "gstNumber": "33GIYPP9938Q1ZM"
      },
      {
        "id": "73",
        "ownerName": "N. Tharun Kumar",
        "branchCode": "IPG050",
        "companyName": "Honey Packers And Movers",
        "mobileNumber": "7396982842",
        "whatsApp": "7396982842",
        "mailIId": "honeypackersandmovers1@gmail.com",
        "website": "https://www.honeypackersandmovers.in/",
        "address": "Munu Swamy Nagar, 5th Lane, Nagaralu, Guntur",
        "state": "Andhra Pradesh",
        "city": "Guntur",
        "gstNumber": "NON"
      },
     
    ]
  };
export default langJSON;